openingHoursOfBuffet = [8, 18]
capacityOfPointB = 38
waitTimeInPointCInSeconds = 30
capacityOfPointD = 200
peakHours = [10, 14]
offPeakHoursDiscrimination = 0.5
minimumPplThatCanComePerHour = 100
maximumPplThatCanComePerHour = 210
peakTimeInSpecificHour = 42 #what is the minute, when the most ppl are expected
probThatNewcomerGoesToBuffet = 66
probThatNewcomerGoesOutOfSys = 74
timeSpentAtChairsE = 300
timeSpentAtChairsG = 480
timeSpentAtTablesF = 900
numberOfPlacesAtEAndGChairs = 7
numberOfPlacesAtTablesF = 73
